version: '2'

services:
  nginx_master:
    build: nginx/
    environment:
      NODE_NAME: "master"
  nginx_slave:
    build: nginx/
    environment:
      NODE_NAME: "slave"
  nginx_loadbalancer:
    build: loadbalancer/
    ports:
      - 80:80
  haproxy:
    build: haproxy/
    # image: haproxy:latest
    volumes:
      - ./keys/domain.com.pem:/etc/ssl/domain.com.pem:ro
      - ./keys/domain.com.crt:/etc/ssl/domain.com.crt:ro
      - ./keys/domain.com.key:/etc/ssl/domain.com.key:ro
    ports:
      - 81:80
      - 443:443
